server:
  port: 8016

logging:
  file:
    name: /fusm-logs/programs.log

spring:
  datasource:
    url: jdbc:postgresql://${db-config.domain}/${db-config.name}
    username: ${db-config.user}
    password: ${db-config.password}
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 10
      minimum-idle: 1
      idle-timeout: 30000
      connection-timeout: 20000
      validation-timeout: 5000

  jpa:
    hibernate:
      ddl-auto: update

  profiles:
    active: prod

ms-program:
  path: /api/v1/program
  trace-path: /api/v1/traceability
